In [1]:
import pandas as pd
import numpy as np

dataset=pd.read_csv("inppp.csv")
columns=len(dataset.columns)

x=dataset.iloc[:,:-1].values
y=dataset.iloc[:,columns-1].values

rows=x.shape[0]

weight=np.full((columns-2,columns-1),0.1)
weight[0]=[0.3,0.05,0.2]
weight[1]=[0.15,0.1,0.2]

final_layer_weight=np.full(columns-1,0.1)
final_layer_weight=[0.5,0.5,0.5]
print(weight)
print("x",x)
z_output=np.full(columns-1,0)
print(z_output)
z_list=[]
learning_rate=0.5

def activation_function(x):
	if x>=0:
		return 1
	else:
		return -1

iteration=0
flag=True
while iteration<3:
	for j in range(rows):
		z_list=[]
		z_list_value=[]
		for i in range(columns-2):
			out=np.dot(np.transpose(x[j]),weight[i])
			z_list_value.append(out)
			z_list.append(activation_function(out))
		z_list.insert(0,1) #adding bias weight
		min_value=min(z_list,key=abs)
		min_value_index=z_list.index(min_value)

		z_output=np.array(z_list)
		y_out=activation_function(np.dot(np.transpose(z_output),final_layer_weight))
		print("y_out ",y_out)

		if(y_out!=y[j] and y[j]==1):
			weight[min_value_index]=weight[min_value_index]+x[j]*(learning_rate*(y[j]-z_list_value[min_value_index]))
			# print("when 1 ",weight[min_value_index])
			flag=True
		elif(y_out!=y[j] and y[j]==-1):
			for i in range(len(z_list_value)):
				if(z_list_value[i]>0):
					weight[i]=weight[i]+x[j]*(learning_rate*(y[j]-z_list_value[min_value_index]))
			flag=True
		else:
			flag=False
		print("Updated weight",weight)
	iteration=iteration+1
print("iteration ",iteration)

[[0.3  0.05 0.2 ]
 [0.15 0.1  0.2 ]]
x [[ 1  1  1]
 [ 1  1 -1]
 [ 1 -1  1]
 [ 1 -1 -1]]
[0 0 0]
y_out  1
Updated weight [[-0.475 -0.725 -0.575]
 [-0.625 -0.675 -0.575]]
y_out  -1
Updated weight [[ 0.3375  0.0875 -1.3875]
 [-0.625  -0.675  -0.575 ]]
y_out  -1
Updated weight [[ 1.40625 -0.98125 -0.31875]
 [-0.625   -0.675   -0.575  ]]
y_out  1
Updated weight [[-0.446875  0.871875  1.534375]
 [-2.478125  1.178125  1.278125]]
y_out  1
Updated weight [[-1.9265625 -0.6078125  0.0546875]
 [-2.478125   1.178125   1.278125 ]]
y_out  -1
Updated weight [[-0.13203125  1.18671875 -1.73984375]
 [-2.478125    1.178125    1.278125  ]]
y_out  -1
Updated weight [[ 1.89726563 -0.84257813  0.28945312]
 [-2.478125    1.178125    1.278125  ]]
y_out  1
Updated weight [[ 0.17207031  0.88261719  2.01464844]
 [-2.478125    1.178125    1.278125  ]]
y_out  1
Updated weight [[-1.86259766 -1.15205078 -0.02001953]
 [-2.478125    1.178125    1.278125  ]]
y_out  -1
Updated weight [[ 0.1347168   0.84526367 -2.01733398]