In [1]:
import numpy as np
import random
import pandas as pd
import math

dta = pd.read_csv("backp.csv")
a = dta.iloc[:,:-2].values
y=np.array(([1,0]), np.float32)
y2 = np.array(([0,1]), np.float32)
#print("a ",a)
#print("y: ",y)
print("................Backpropagation 2 layer model.............\n\n")
w1 = np.array(([[0.1,0,0.3], [-0.2,0.2,-0.4]]), np.float32)
w2 = np.array(([[-0.4,0.2],[0.1,-0.1],[0.6,-0.2]]), np.float32)

b1 = np.array(([0.1,0.2,0.5]), np.float32)
b2 = np.array(([-0.1,0.6]), np.float32)

t=0
eta=0.1

def appsig(Z):
    for i in range(len(Z)):
        Z[i] = 1/(1+math.exp(-Z[i]))
    return Z
    
def calerr(Z):
    x= np.ones((2), np.float64)
    for i in range(2):
        x[i] = Z[i]*(1-Z[i])*(y[i]-Z[i])
    return x

def updwgts(w,delt,p,Z):
    if p==1:
        at = Z
    else:
        at = a
    for i in range(len(w)):
        w[i]=w[i]+(eta*at[p][i]*delt[i])
        
    return w
    
    

def calerr2(Z, delt, w):
    x= np.ones((3), np.float64)
    t=1
    for i in range(3):
        a = w[i].reshape(2,1)
        x[i] = Z[i]*(1-Z[i])*np.dot(delt,w[i])
        t+=1
    return x

for i in range(2):
    Z=[]
    Z1=[]
    delt=[]
    delta=[]
    print("\n\nPattern: ",i+1)
    print()
    print("a[i]: ",a[i])
    print(w1)
    Z = np.dot(a[i],w1)+b1
    print()
    print("The input for hidden layers ",Z)
    Z = appsig(Z)
    print("The input for hidden layers with applying sigmoid ",Z)
    Z1 = np.dot(Z,w2)+b2
    Z1= appsig(Z1)
    
    #To calculate error of output layer 
    print()
    print("The The output of hidden layer with activtion function ",Z1)
    delta1= np.ones((2),np.float64)
    if not np.array_equal(y, Z1):
        delt = calerr(Z1)
        delta1=delt
        print(delt)
        delt = calerr2(Z,delta1,w2)
        print(delt)
        
    #Update the weights
    print("\nUpdated Weights are now: ")
    w1= updwgts(w1,delt,0,Z)
    print(w1)

................Backpropagation 2 layer model.............




Pattern:  1

a[i]:  [0.6 0.1]
[[ 0.1  0.   0.3]
 [-0.2  0.2 -0.4]]

The input for hidden layers  [0.14       0.22       0.64000001]
The input for hidden layers with applying sigmoid  [0.53494295 0.55477924 0.65475346]

The The output of hidden layer with activtion function  [0.53353778 0.6272787 ]
[ 0.11609089 -0.14665784]
[-0.01884947  0.00648987  0.02237594]

Updated Weights are now: 
[[ 0.09886903 -0.00113097  0.29886904]
 [-0.19993511  0.2000649  -0.3999351 ]]


Pattern:  2

a[i]:  [0.2 0.3]
[[ 0.09886903 -0.00113097  0.29886904]
 [-0.19993511  0.2000649  -0.3999351 ]]

The input for hidden layers  [0.05979328 0.25979328 0.43979328]
The input for hidden layers with applying sigmoid  [0.51494387 0.56458547 0.60820977]

The The output of hidden layer with activtion function  [0.52881974 0.6282901 ]
[ 0.11740371 -0.14673191]
[-0.01905993  0.00649321  0.02377869]

Updated Weights are now: 
[[ 0.09772544 -0.00227456  0.29772