In [17]:
import numpy as np
import pandas as pd

print("........Bayesian Classification for AND gate.............")
def load_dataset():
    dataset=pd.read_csv("basi.csv")
    dataset = dataset.sample(frac=1).reset_index(drop=True)
    columns=len(dataset.columns)
    x=dataset.iloc[:,:-1].values
    y=dataset.iloc[:,columns-1].values
    y=y.reshape(y.shape[0],1)
    return x,y

train_size=0

def get_train_and_test_dataset(x,y):
    global train_size
    m=y.size
    train_size=int(m*0.7)
    x_train=x[:train_size]
    x_test=x[train_size:]
    y_train=y[:train_size]
    y_test=y[train_size:]
    print("training data size is ", train_size)
    return x_train,x_test,y_train,y_test

x,y=load_dataset()
print("x",x)
print("y",y)
m=y.shape[0]

x_train,x_test,y_train,y_test=get_train_and_test_dataset(x,y)

total_positive_class=np.count_nonzero(y==1)
print("Total positive samples ",total_positive_class)
total_negative_class=m - total_positive_class
print("Total negative samples ",total_negative_class)

def cal_prob(feature_column_index,value,class_type,x,y):
    global total_positive_class,total_negative_class,train_size
    count=0
    for i in range(train_size):
        if y[i]==class_type and x[i][feature_column_index]==value:
            count+=1
    if class_type==0:
        return count/total_negative_class
    else:
        return count/total_positive_class

def oyes(x_test,x,y):
    global total_positive_class,m
    res=total_positive_class/m
    for i in range(x_test.size):
        res=res*cal_prob(i,x_test[i],1,x,y)
    return res

def ono(x_test,x,y):
    global total_negative_class,m
    res=total_negative_class/m
    print(x_test[0])
    for i in range(x_test.shape[0]):
        res=res*cal_prob(i,x_test[i],0,x,y)
    return res

def check_tst_set(x_test,x_train,y_train):
    print("test for sample: ", x_test[0])
    prob_yes=oyes(x_test[0],x_train,y_train)
    prob_no=ono(x_test[0],x_train,y_train)
    print("Probability of yes: ",prob_yes)
    print("Probability of no: ",prob_no)

    if prob_yes>prob_no:
        print("Samples belongs to the positive class")
    else:
        print("Sample belongs to the negative class")


check_tst_set(x_test,x_train,y_train)

........Bayesian Classification for AND gate.............
x [[1 1 1]
 [0 0 1]
 [0 1 1]
 [0 1 0]
 [0 0 0]
 [1 0 0]
 [1 1 0]
 [1 0 1]]
y [[1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]]
training data size is  5
Total positive samples  1
Total negative samples  7
test for sample:  [1 0 0]
1
Probability of yes:  0.0
Probability of no:  0.0
Sample belongs to the negative class
